- hosts: workstation
  gather_facts: false



  tasks:
  - name: OpenStack servers
    os_server_facts:
     cloud: ospcloud
     server: 'frontend'
    register: openstack_info
    tags:
      - osp.smoke

  - name: Frontend IP public
    debug:
      msg: "{{ openstack_info.ansible_facts.openstack_servers[0].public_v4 }}"

  - name: Curl website
    uri:
      url: http://{{ openstack_info.ansible_facts.openstack_servers[0].public_v4 }}
      return_content: yes
    register: webpageoutput
    ignore_errors: yes
    tags:
      - osp.smoke

  - name: OUTPUT OF CURL
    debug: 
      var: webpageoutput.content

  - name: Fail if 'Ansible has done its job' is not in the page content
    fail:
    when: "'Ansible has done its job' not in webpageoutput.content"
    tags:
      - osp.smoke
